version: "3"

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: changeme
    volumes:
      - db:/var/lib/mysql



  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data


  app:
    image: nextcloud
    restart: always
    environment:
      VIRTUAL_HOST: cloud.paulnetwork.org
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: changeme
      REDIS_HOST: redis
    volumes:
      - nextcloud:/var/www/html
    depends_on:
      - db
      - redis

  web:
    image: nginx
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./letsencrypt:/etc/nginx/ssl:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app

volumes:
  db:
  nextcloud:
  redis:
